apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-bridge
  # It must be deployed in the same namespace where the pods need the secrets!
  namespace: obs-shared 
spec:
  provider: azure
  # This tells it to generate native K8s secrets so Grafana can use them
  secretObjects:
  - secretName: obs-shared-secrets  # <--- CHANGED THIS LINE!
    type: Opaque
    data:
    {{- range .Values.secrets }}
    - objectName: {{ .secretName }}
      key: {{ .k8sKey }}
    {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "" # We will use Workload Identity later
    keyvaultName: {{ .Values.keyvaultName }}
    cloudName: ""
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .secretName }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.tenantId }}
