# If you ever need to add a QA namespace to the app cluster later, you don't touch the template. 
# You just add - name: logitrack-qa to this values file! That is the power of Helm.
# Render cmd - helm template test-render ./base-charts/namespace-setup -f clusters/aks-app-01/name-space-onboard/values.yaml > ns-app.yaml 

environment: prod-app
namespaces:
  - name: logitrack-app


