---
# Source: logitrack/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: logitrack
  namespace: logitrack-app
  labels:
    app: logitrack
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: logitrack
---
# Source: logitrack/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logitrack
  namespace: logitrack-app
  labels:
    app: logitrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logitrack
  template:
    metadata:
      labels:
        app: logitrack
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      # Enterprise Security applied to the Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: logitrack
          image: "valkiacr002.azurecr.io/logitrack:prod-v1.0.0-RELEASE"
          imagePullPolicy: Always
          
          # Container-level security
          securityContext:
            allowPrivilegeEscalation: false
            
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.logitrack-app.svc.cluster.local:4317"
            - name: PYROSCOPE_SERVER_ADDRESS
              value: "http://alloy.logitrack-app.svc.cluster.local:4040"
            # Add these two lines to stop redundant OTLP pushes!
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
              
          # Kubernetes Health Inspectors
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
