# Environment: aks-app-01
image:
  repository: valkiacr002.azurecr.io/logitrack
  tag: prod-v1.0.0-RELEASE

# Push data to the LOCAL Alloy Delivery Truck!
observability:
  tempoEndpoint: "http://alloy.logitrack-app.svc.cluster.local:4317"
  pyroscopeEndpoint: "http://alloy.logitrack-app.svc.cluster.local:4040"