name: 09 - Deploy Grafana Alloy

run-name: "Deploy Alloy | Cluster: aks-app-01 | CR: ${{ inputs.cr_number }} | Description: ${{ inputs.cr_description }} | By @${{ github.actor }}"


on:
  workflow_dispatch:
    inputs:
      cr_number:
        description: 'Change Request (CR) Number'
        required: true
        type: string

      cr_description:
        description: 'Notes about the change request'
        required: true
        type: string

env:
  RESOURCE_GROUP: "valki-ent-rg"

jobs:
  deploy-alloy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Add Grafana Helm Repo
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
      
      - name: Connect to AKS Cluster
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name aks-app-01 --overwrite-existing
          
      # The Validation Step
      - name: Render Helm Chart (Validation & Dry Run)
        run: |
          echo "Compiling Helm templates to verify YAML syntax..."
          # CHANGED: Now targeting logitrack-app
          helm template alloy grafana/alloy \
            --namespace logitrack-app \
            -f clusters/aks-app-01/alloy/values.yaml > rendered-alloy.yaml
          
          echo "--- RENDERED OUTPUT FOR DEBUGGING ---"
          cat rendered-alloy.yaml

      - name: Deploy Grafana Alloy via Helm
        run: |
          echo "Syntax is valid. Deploying Alloy..."
          # CHANGED: Now targeting logitrack-app
          helm upgrade --install alloy grafana/alloy \
            --namespace logitrack-app \
            -f clusters/aks-app-01/alloy/values.yaml